parameters:
#    investigigadores_lineas.example.class: DEPI\InvestigadoresLineasBundle\Example

services:
#    investigigadores_lineas.example:
#        class: %investigigadores_lineas.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
