security:
    firewalls:
        backend:
            pattern: ^/*
            anonymous: ~
            form_login: ~

    access_control:
        - { path: ^/usuario/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/*, roles: ROLE_USUARIO }

    providers:
        usuarios:
            entity: { class: DEPI\UsuarioBundle\Entity\Usuario, property: email }

    encoders:
        DEPI\UsuarioBundle\Entity\Usuario: { algorithm: sha512, iterations: 10 }