alumnos:
    pattern:  /alumnos
    defaults: { _controller: AlumnosBundle:Alumnos:index }

_alumnos:
    pattern: /alumnos/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: alumnos}

alumnos_new:
    pattern:  /alumnos/new
    defaults: { _controller: AlumnosBundle:Alumnos:new }

alumnos_edit:
    pattern:  /alumnos/edit/{id}
    defaults: { _controller: AlumnosBundle:Alumnos:edit }

alumnos_show:
    pattern:  /alumnos/show/{id}
    defaults: { _controller: AlumnosBundle:Alumnos:show }

alumnos_create:
    pattern:  /alumnos/create
    defaults: { _controller: AlumnosBundle:Alumnos:create }

alumnos_update:
    pattern:  /alumnos/update/{id}
    defaults: { _controller: AlumnosBundle:Alumnos:update }

alumnos_delete:
    pattern:  /alumnos/delete/{id}
    defaults: { _controller: AlumnosBundle:Alumnos:delete }