posgradmin:
    pattern:  /posgradmin
    defaults: { _controller: BackEndBundle:Default:index }

_posgradmin:
    pattern: /posgradmin/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: posgradmin}
