parameters:
#    back_end.example.class: DEPI\BackEndBundle\Example

services:
#    back_end.example:
#        class: %back_end.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
