investigadores:
    pattern:  /posgradmin/investigadores
    defaults: { _controller: InvestigadoresBundle:Investigadores:index }

_investigadores:
    pattern: /posgradmin/investigadores/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: investigadores}

investigadores_new:
    pattern:  /posgradmin/investigadores/new
    defaults: { _controller: InvestigadoresBundle:Investigadores:new }

investigadores_edit:
    pattern:  /posgradmin/investigadores/edit/{id}
    defaults: { _controller: InvestigadoresBundle:Investigadores:edit }

investigadores_create:
    pattern:  /posgradmin/investigadores/create
    defaults: { _controller: InvestigadoresBundle:Investigadores:create }

investigadores_update:
    pattern:  /posgradmin/investigadores/update/{id}
    defaults: { _controller: InvestigadoresBundle:Investigadores:update }

investigadores_delete:
    pattern:  /posgradmin/investigadores/delete/{id}
    defaults: { _controller: InvestigadoresBundle:Investigadores:delete }