parameters:
#    investigadores.example.class: DEPI\InvestigadoresBundle\Example

services:
#    investigadores.example:
#        class: %investigadores.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
