parameters:
#    portada.example.class: DEPI\PortadaBundle\Example
    fuz_tools.twig.asset_exists_extension.class: DEPI\PortadaBundle\Twig\Extension\FileExistsExtension

services:
#    portada.example:
#        class: %portada.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    fuz_tools.twig.asset_exists_extension:
        class: '%fuz_tools.twig.asset_exists_extension.class%'
        arguments: ['@kernel']
        tags:
          - { name: twig.extension }