usuario_login:
    pattern:  /posgradmin/login
    defaults: { _controller: UsuarioBundle:Usuario:login }

usuario_login_check:
    pattern:  /posgradmin/login_check

usuario_logout:
    pattern:  /posgradmin/logout
