investigadorproyecto:
    pattern:  /posgradmin/investigadorproyecto
    defaults: { _controller: InvestigadorProyectoBundle:InvestigadorProyecto:index }

_investigadorproyecto:
    pattern: /posgradmin/investigadorproyecto/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: investigadorproyecto}

investigadorproyecto_new:
    pattern:  /posgradmin/investigadorproyecto/new
    defaults: { _controller: InvestigadorProyectoBundle:InvestigadorProyecto:new }

investigadorproyecto_edit:
    pattern:  /posgradmin/investigadorproyecto/edit/{id}
    defaults: { _controller: InvestigadorProyectoBundle:InvestigadorProyecto:edit }

investigadorproyecto_create:
    pattern:  /posgradmin/investigadorproyecto/create
    defaults: { _controller: InvestigadorProyectoBundle:InvestigadorProyecto:create }

investigadorproyecto_update:
    pattern:  /posgradmin/investigadorproyecto/update/{id}
    defaults: { _controller: InvestigadorProyectoBundle:InvestigadorProyecto:update }

investigadorproyecto_delete:
    pattern:  /posgradmin/investigadorproyecto/delete/{id}
    defaults: { _controller: InvestigadorProyectoBundle:InvestigadorProyecto:delete }