productosacademicos:
    pattern:  /posgradmin/productosacademicos
    defaults: { _controller: ProductosAcademicosBundle:ProductosAcademicos:index }

_productosacademicos:
    pattern: /posgradmin/productosacademicos/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: productosacademicos}

productosacademicos_new:
    pattern:  /posgradmin/productosacademicos/new
    defaults: { _controller: ProductosAcademicosBundle:ProductosAcademicos:new }

productosacademicos_edit:
    pattern:  /posgradmin/productosacademicos/edit/{id}
    defaults: { _controller: ProductosAcademicosBundle:ProductosAcademicos:edit }

productosacademicos_show:
    pattern:  /posgradmin/productosacademicos/show/{id}
    defaults: { _controller: ProductosAcademicosBundle:ProductosAcademicos:show }

productosacademicos_create:
    pattern:  /posgradmin/productosacademicos/create
    defaults: { _controller: ProductosAcademicosBundle:ProductosAcademicos:create }

productosacademicos_update:
    pattern:  /posgradmin/productosacademicos/update/{id}
    defaults: { _controller: ProductosAcademicosBundle:ProductosAcademicos:update }

productosacademicos_delete:
    pattern:  /posgradmin/productosacademicos/delete/{id}
    defaults: { _controller: ProductosAcademicosBundle:ProductosAcademicos:delete }